"""add application relation to interviews

Revision ID: 1fcf7ce89052
Revises: 88ef1e687481
Create Date: 2026-09-13 09:09:05.855882

"""

# Tuna-import Alembic operations.
from alembic import op

# Tuna-import SQLAlchemy kwa ajili ya sa.Column, sa.Integer, sa.String n.k.
import sqlalchemy as sa

# Tuna-import PostgreSQL types ikiwa migration itahitaji.
from sqlalchemy.dialects import postgresql

# Tuna-import typing utilities.
from typing import Sequence, Union


# Revision ID ya migration hii.
revision: str = '1fcf7ce89052'

# Revision iliyotangulia.
down_revision: Union[str, None] = '88ef1e687481'

# Branch labels.
branch_labels: Union[str, Sequence[str], None] = None

# Dependencies.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Alembic itaweka commands za kuongeza/kubadilisha database hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('application_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_foreign_key(None, 'interviews', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # Alembic itaweka commands za kurudisha database nyuma hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_column('interviews', 'application_id')
    # ### end Alembic commands ###