"""add attention events

Revision ID: 2c57083d032d
Revises: 6c14800261f0
Create Date: 2026-09-24 22:51:37.088240

"""

# Tuna-import Alembic operations.
from alembic import op

# Tuna-import SQLAlchemy kwa ajili ya sa.Column, sa.Integer, sa.String n.k.
import sqlalchemy as sa

# Tuna-import PostgreSQL types ikiwa migration itahitaji.
from sqlalchemy.dialects import postgresql

# Tuna-import typing utilities.
from typing import Sequence, Union


# Revision ID ya migration hii.
revision: str = '2c57083d032d'

# Revision iliyotangulia.
down_revision: Union[str, None] = '6c14800261f0'

# Branch labels.
branch_labels: Union[str, Sequence[str], None] = None

# Dependencies.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Alembic itaweka commands za kuongeza/kubadilisha database hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attention_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_events_id'), 'attention_events', ['id'], unique=False)
    op.create_index(op.f('ix_attention_events_interview_id'), 'attention_events', ['interview_id'], unique=False)
    op.alter_column('interviews', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # Alembic itaweka commands za kurudisha database nyuma hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_attention_events_interview_id'), table_name='attention_events')
    op.drop_index(op.f('ix_attention_events_id'), table_name='attention_events')
    op.drop_table('attention_events')
    # ### end Alembic commands ###