"""add title and created at to interviews

Revision ID: 40a102d9beed
Revises: a53a4f2675b9
Create Date: 2026-09-06 20:12:41.074931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a102d9beed'
down_revision: Union[str, Sequence[str], None] = 'a53a4f2675b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('interviews', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'created_at')
    op.drop_column('interviews', 'title')
    # ### end Alembic commands ###
