"""add attention sessions

Revision ID: 6c14800261f0
Revises: 81c986116d96
Create Date: 2026-09-24 09:38:38.795944

"""

# Tuna-import Alembic operations.
from alembic import op

# Tuna-import SQLAlchemy kwa ajili ya sa.Column, sa.Integer, sa.String n.k.
import sqlalchemy as sa

# Tuna-import PostgreSQL types ikiwa migration itahitaji.
from sqlalchemy.dialects import postgresql

# Tuna-import typing utilities.
from typing import Sequence, Union


# Revision ID ya migration hii.
revision: str = '6c14800261f0'

# Revision iliyotangulia.
down_revision: Union[str, None] = '81c986116d96'

# Branch labels.
branch_labels: Union[str, Sequence[str], None] = None

# Dependencies.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Alembic itaweka commands za kuongeza/kubadilisha database hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attention_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_sessions_id'), 'attention_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_attention_sessions_interview_id'), 'attention_sessions', ['interview_id'], unique=False)
    op.alter_column('interviews', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # Alembic itaweka commands za kurudisha database nyuma hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_attention_sessions_interview_id'), table_name='attention_sessions')
    op.drop_index(op.f('ix_attention_sessions_id'), table_name='attention_sessions')
    op.drop_table('attention_sessions')
    # ### end Alembic commands ###