"""add attention metrics

Revision ID: 81c986116d96
Revises: 1fcf7ce89052
Create Date: 2026-09-24 04:26:15.408067

"""

# Tuna-import Alembic operations.
from alembic import op

# Tuna-import SQLAlchemy kwa ajili ya sa.Column, sa.Integer, sa.String n.k.
import sqlalchemy as sa

# Tuna-import PostgreSQL types ikiwa migration itahitaji.
from sqlalchemy.dialects import postgresql

# Tuna-import typing utilities.
from typing import Sequence, Union


# Revision ID ya migration hii.
revision: str = '81c986116d96'

# Revision iliyotangulia.
down_revision: Union[str, None] = '1fcf7ce89052'

# Branch labels.
branch_labels: Union[str, Sequence[str], None] = None

# Dependencies.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Alembic itaweka commands za kuongeza/kubadilisha database hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attention_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('gaze_deviation_deg', sa.Float(), nullable=True),
    sa.Column('face_detected', sa.Boolean(), nullable=False),
    sa.Column('off_screen', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_metrics_id'), 'attention_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_attention_metrics_interview_id'), 'attention_metrics', ['interview_id'], unique=False)
    op.alter_column('interviews', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # Alembic itaweka commands za kurudisha database nyuma hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_attention_metrics_interview_id'), table_name='attention_metrics')
    op.drop_index(op.f('ix_attention_metrics_id'), table_name='attention_metrics')
    op.drop_table('attention_metrics')
    # ### end Alembic commands ###