"""add applications table

Revision ID: 88ef1e687481
Revises: d6508e7bb056
Create Date: 2026-09-12 12:33:56.805442

"""

# Tuna-import Alembic operations.
from alembic import op

# Tuna-import SQLAlchemy kwa ajili ya sa.Column, sa.Integer, sa.String n.k.
import sqlalchemy as sa

# Tuna-import PostgreSQL types ikiwa migration itahitaji.
from sqlalchemy.dialects import postgresql

# Tuna-import typing utilities.
from typing import Sequence, Union


# Revision ID ya migration hii.
revision: str = '88ef1e687481'

# Revision iliyotangulia.
down_revision: Union[str, None] = 'd6508e7bb056'

# Branch labels.
branch_labels: Union[str, Sequence[str], None] = None

# Dependencies.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Alembic itaweka commands za kuongeza/kubadilisha database hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.execute("UPDATE interviews SET created_at = 'NOW()' WHERE created_at IS NULL")
    op.alter_column('interviews', 'created_at',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # Alembic itaweka commands za kurudisha database nyuma hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###