"""fix interview finished at column

Revision ID: a53a4f2675b9
Revises: 64ae8aebdea5
Create Date: 2026-09-06 16:09:29.107543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a53a4f2675b9'
down_revision: Union[str, Sequence[str], None] = '64ae8aebdea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.alter_column('interviews', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('interviews', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('interviews', 'created_at')
    op.drop_column('interviews', 'title')
    op.drop_column('interviews', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('interviews', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('interviews', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('interviews', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('interviews', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('interviews', 'finished_at')
    # ### end Alembic commands ###
