"""add jobs table

Revision ID: d6508e7bb056
Revises: 411eb1f2add3
Create Date: 2026-09-11 11:31:36.481433

"""

# Tuna-import Alembic operations.
from alembic import op

# Tuna-import SQLAlchemy kwa ajili ya sa.Column, sa.Integer, sa.String n.k.
import sqlalchemy as sa

# Tuna-import PostgreSQL types ikiwa migration itahitaji.
from sqlalchemy.dialects import postgresql

# Tuna-import typing utilities.
from typing import Sequence, Union


# Revision ID ya migration hii.
revision: str = 'd6508e7bb056'

# Revision iliyotangulia.
down_revision: Union[str, None] = '411eb1f2add3'

# Branch labels.
branch_labels: Union[str, Sequence[str], None] = None

# Dependencies.
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Alembic itaweka commands za kuongeza/kubadilisha database hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=False),
    sa.Column('education_required', sa.String(length=150), nullable=True),
    sa.Column('experience_required', sa.Integer(), nullable=True),
    sa.Column('skills_required', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_employer_id'), 'jobs', ['employer_id'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.execute("UPDATE interviews SET title = 'Untitled' WHERE title IS NULL ")
    op.alter_column('interviews', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('interviews', 'title',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # Alembic itaweka commands za kurudisha database nyuma hapa.
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('interviews', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_employer_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###